"""add continent region farm variety altitude to beans

Revision ID: 3e2067981192
Revises: 93d5046f9c6f
Create Date: 2026-07-02 09:18:09.267731

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3e2067981192"
down_revision: Union[str, Sequence[str], None] = "93d5046f9c6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("beans", sa.Column("continent", sa.String(length=100), nullable=True))
    op.add_column("beans", sa.Column("region", sa.String(length=255), nullable=True))
    op.add_column("beans", sa.Column("farm", sa.String(length=255), nullable=True))
    op.add_column("beans", sa.Column("variety", sa.String(length=255), nullable=True))
    op.add_column("beans", sa.Column("altitude", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("beans", "altitude")
    op.drop_column("beans", "variety")
    op.drop_column("beans", "farm")
    op.drop_column("beans", "region")
    op.drop_column("beans", "continent")
    # ### end Alembic commands ###
