"""create beans brews brew_parameters tables

Revision ID: 93d5046f9c6f
Revises: 
Create Date: 2026-06-18 16:52:07.381160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93d5046f9c6f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('roaster', sa.String(length=255), nullable=True),
    sa.Column('origin', sa.String(length=255), nullable=True),
    sa.Column('process', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('roast_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bean_id', sa.Integer(), nullable=True),
    sa.Column('brewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('grind_size', sa.String(length=50), nullable=True),
    sa.Column('water_temp_celsius', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('coffee_grams', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('water_grams', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('bloom_time_seconds', sa.Integer(), nullable=True),
    sa.Column('total_time_seconds', sa.Integer(), nullable=True),
    sa.Column('tasting_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['bean_id'], ['beans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brew_parameters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brew_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['brew_id'], ['brews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brew_parameters')
    op.drop_table('brews')
    op.drop_table('beans')
    # ### end Alembic commands ###
